services:
  postgres:
    image: postgres
    container_name: meu_blog_postgres
    environment:
      POSTGRES_USER: dry
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blog_2024
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha_rede

volumes:
  postgres_data:

networks:
  minha_rede:
